name: Create backend Docker image
on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      packages: write
      deployments: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        push: true
        tags: ghcr.io/coltonherrod/deployview-frontend:latest

