name: Deploy Frontend to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Deploy to AWS Amplify
      run: |
        aws amplify start-deployment \
          --app-id ${{ secrets.AMPLIFY_APP_ID }} \
          --branch-name main \
          --source ./build
